version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: idnomo
      MYSQL_DATABASE: ipmanager
      MYSQL_USER: omondi
      MYSQL_PASSWORD: idnomo
    ports:
      - "3306:3306"
    networks:
        - ipmanager-spring

  ipmanager:
    build: .
    restart: always
    container_name: ipmanager
    ports:
      - "8080:8080"
    networks:
      - ipmanager-spring
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/ipmanager?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysql
    volumes:
      - .m2:/root/.m2

networks:
    ipmanager-spring:
        driver: bridge

